"use client";

import { motion } from "framer-motion";

const SUMMARY = [
  { label: "Customer Sentiment", value: "Positive" },
  { label: "Main Objection", value: "Pricing" },
  { label: "Deal Risk", value: "Low" },
  { label: "Next Step", value: "Schedule product demo" },
];

interface CallSummaryProps {
  /** When true, panel animates in (e.g. after demo completes or on scroll) */
  visible?: boolean;
}

export default function CallSummary({ visible = true }: CallSummaryProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={visible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
      transition={{ duration: 0.5 }}
      className="mt-8 rounded-xl border border-purple-500/30 bg-black/40 backdrop-blur-xl p-5 md:p-6 shadow-[0_0_40px_-10px_rgba(139,92,246,0.25)] hover:shadow-[0_0_48px_-8px_rgba(139,92,246,0.35)] transition-shadow duration-300"
    >
      <p className="text-xs font-medium text-purple-300/90 uppercase tracking-wider mb-4">
        Call Summary Generated by AI
      </p>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {SUMMARY.map((item, i) => (
          <div key={item.label} className="flex flex-col gap-0.5">
            <span className="text-[11px] text-neutral-500 uppercase tracking-wider">
              {item.label}
            </span>
            <span className="text-sm font-semibold text-foreground">{item.value}</span>
          </div>
        ))}
      </div>
    </motion.div>
  );
}
